services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sales_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build: ./sales-auth-service
    container_name: auth-service
    ports:
      - "3001:3000"
    env_file:
      - ./sales-auth-service/.env
    depends_on:
      - rabbitmq
      - mysql-db
  
  customer-service:
    build: ./sales-customer-service
    container_name: customer-service
    ports:
      - "3002:3000"
    env_file:
      - ./sales-customer-service/.env
    depends_on:
      - auth-service


  order-service:
    build: ./sales-order-service
    container_name: order-service
    ports:
      - "3003:3000"
    env_file:
      - ./sales-order-service/.env
    depends_on:
      - customer-service


  notification-service:
    build: ./sales-notification-service
    container_name: notification-service
    env_file:
      - ./sales-notification-service/.env
    depends_on:
      - rabbitmq
  
volumes:
  mysql_data: