services:

  mysql:
    image: mysql:8.4
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - auth-service
      - customer-service
      - order-service
      - invoice-service
      - payment-service
    networks:
      - backend

  frontend:
    build: ./sales-frontend-ui
    container_name: sales-frontend-ui
    restart: always
    networks:
      - backend

  auth-service:
    build: ./sales-auth-service
    container_name: auth-service
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - ENVIRONMENT=${ENVIRONMENT}
      - SERVICE_NAME=auth-service
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - backend

  customer-service:
    build: ./sales-customer-service
    container_name: customer-service
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ENVIRONMENT=${ENVIRONMENT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SERVICE_NAME=customer-service
    depends_on:
      - mysql
    networks:
      - backend

  order-service:
    build: ./sales-order-service
    container_name: order-service
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CUSTOMER_SERVICE_URL=http://customer-service:3000
      - ENVIRONMENT=${ENVIRONMENT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SERVICE_NAME=order-service
      - API_VERSION=${API_VERSION}
    depends_on:
      - customer-service
      - rabbitmq
      - mysql
    networks:
      - backend

  invoice-service:
    build: ./sales-invoice-service
    container_name: invoice-service
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ORDER_SERVICE_URL=http://order-service:3000
      - API_VERSION=${API_VERSION}
      - ENVIRONMENT=${ENVIRONMENT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SERVICE_NAME=invoice-service
    depends_on:
      - order-service
      - mysql
    networks:
      - backend

  payment-service:
    build: ./sales-payment-service
    container_name: payment-service
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - INVOICE_SERVICE_URL=http://invoice-service:3000
      - ENVIRONMENT=${ENVIRONMENT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SERVICE_NAME=payment-service
    depends_on:
      - invoice-service
      - mysql
    networks:
      - backend

  notification-service:
    build: ./sales-notification-service
    container_name: notification-service
    restart: always
    env_file:
      - .env
    environment:
      - SERVICE_NAME=notification-service
    depends_on:
      - rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data: